<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                       => __DIR__ . '/Module.php',
    'Application\Controller\AuthController'    => __DIR__ . '/src/Application/Controller/AuthController.php',
    'Application\Controller\SuccessController' => __DIR__ . '/src/Application/Controller/SuccessController.php',
    'Application\Model\MyAuthStorage'          => __DIR__ . '/src/Application/Model/MyAuthStorage.php',
    'Application\Model\User'                   => __DIR__ . '/src/Application/Model/User.php',
);
